/**
 * Shared Markdown → HTML helper (ADR-23).
 *
 * Extracted from src/export/html.ts so that generators can call it without
 * a circular import. The export pipeline re-imports from here; behaviour is
 * unchanged (pure refactor).
 *
 * Pipeline (SG2c refactor — placeholder pattern, no rehype-raw):
 * 1. preprocessMermaidPlaceholders — replace ```mermaid fences with
 *    LBMERMAID_<n> bare-text placeholders; stash rendered SVGs.
 * 2. preprocessDetailsPlaceholders — replace <details>...</details> blocks
 *    with LBDETAILS_<n> tokens so remark-rehype does not alter them.
 * 2b.preprocessRawHtmlPlaceholders — replace all other raw HTML blocks
 *    (div, section, nav, span, select, option, label, etc.) with LBRAW_<n>
 *    tokens so remark-rehype does not strip them. Runs AFTER details so that
 *    nested details inside divs are already tokenized and don't double-match.
 * 3. remark-parse — parse markdown AST.
 * 4. remark-rehype — convert to hast (no allowDangerousHtml needed).
 * 5. rehype-slug — add id attributes to headings for anchor navigation.
 * 6. rehype-stringify — serialize to HTML.
 * 7. wrapPreElements — wrap each <pre> in <div class="lb-pre-wrap"> with
 *    a sibling <button class="lb-copy"> (ADR-26). Runs BEFORE mermaid inject
 *    so SVG blocks are not double-wrapped.
 * 8. injectMermaidSvgs — replace placeholder paragraphs with <div class="mermaid">.
 * 9. injectDetailsDivs — restore <details> blocks from tokens.
 * 9b.injectRawHtmlBlocks — restore raw HTML blocks from LBRAW tokens.
 * 10. injectSpeakerDivs (optional) — replace speaker placeholders.
 */

import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import { preprocessMermaidPlaceholders, injectMermaidSvgs } from "./mermaid.js";
import {
  injectSpeakerDivs,
  type SpeakerBlock,
} from "../generate/speaker-blocks.js";

// ---------------------------------------------------------------------------
// Details placeholder pattern (ADR-23)
// ---------------------------------------------------------------------------

const DETAILS_PLACEHOLDER_PREFIX = "LBDETAILS_";

interface DetailEntry {
  token: string;
  html: string;
}

/**
 * Replace <details>...</details> blocks in `markdown` with unique tokens.
 * Remark-rehype can strip or mangle raw HTML blocks; using placeholders
 * preserves them through the unified pipeline, then `injectDetailsDivs`
 * substitutes them back.
 *
 * Matches block-level <details> elements (multi-line). Greedy-last to avoid
 * nested details from being swallowed (not expected in this codebase, but safe).
 */
export function preprocessDetailsPlaceholders(markdown: string): {
  markdown: string;
  details: DetailEntry[];
} {
  const details: DetailEntry[] = [];
  let counter = 0;

  // Replace <details ...>...</details> blocks with tokens.
  // The regex is intentionally non-greedy on the inner content [\s\S]*? so
  // sequential (not nested) details blocks each get their own token.
  const replaced = markdown.replace(
    /<details[\s\S]*?<\/details>/gi,
    (match) => {
      const token = `${DETAILS_PLACEHOLDER_PREFIX}${counter++}`;
      details.push({ token, html: match });
      return token;
    }
  );

  return { markdown: replaced, details };
}

/**
 * After unified pipeline, restore <details> blocks from their tokens.
 * The pipeline wraps each token in a <p> tag; replace the whole <p> element.
 */
export function injectDetailsDivs(html: string, details: DetailEntry[]): string {
  let result = html;
  for (const entry of details) {
    // rehype-stringify wraps bare text paragraphs as <p>TOKEN</p>
    const wrappedToken = `<p>${entry.token}</p>`;
    if (result.includes(wrappedToken)) {
      result = result.replace(wrappedToken, entry.html);
    } else {
      // Fallback: try plain token in case no <p> wrapper was added.
      result = result.replace(entry.token, entry.html);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Raw HTML block placeholder pattern (CRITICAL-1 fix)
// ---------------------------------------------------------------------------

const RAW_HTML_PLACEHOLDER_PREFIX = "LBRAW_";

interface RawHtmlEntry {
  token: string;
  html: string;
}

/**
 * Block-level HTML tags whose raw blocks remark-rehype strips by default.
 * This list covers all tags generated by the dashboard, sessions, resources,
 * and milestones generators. Sorted longest-first so alternation is safe.
 */
const BLOCK_HTML_TAGS = [
  "section",
  "article",
  "select",
  "option",
  "label",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "figure",
  "aside",
  "main",
  "nav",
  "div",
  "span",
  "form",
  "ul",
  "ol",
  "li",
  "dl",
  "dt",
  "dd",
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
];

// Regex: matches a block-level raw HTML element that starts at the beginning
// of a line. We match greedily from the opening tag to the corresponding
// closing tag. The match is multiline and case-insensitive.
//
// Strategy: scan the markdown line by line. When a line starts with one of the
// known opening tags, collect lines until we find the matching closing tag.
// This approach handles multi-line blocks without a single complex regex.

/**
 * Replace raw HTML blocks (div, section, nav, select, etc.) in `markdown`
 * with unique LBRAW_<n> tokens. remark-rehype does not alter unknown inline
 * text, so the tokens pass through unchanged, then `injectRawHtmlBlocks`
 * restores them after the unified pipeline.
 *
 * Must run AFTER `preprocessDetailsPlaceholders` so nested <details> inside
 * divs are already tokenized and don't produce partial matches here.
 */
export function preprocessRawHtmlPlaceholders(markdown: string): {
  markdown: string;
  rawBlocks: RawHtmlEntry[];
} {
  const rawBlocks: RawHtmlEntry[] = [];
  let counter = 0;

  // Build an alternation pattern for opening tags we handle.
  const tagAlt = BLOCK_HTML_TAGS.join("|");
  // Matches a block-level opening tag at the START of a line (after optional
  // whitespace). Capture group 1 = the tag name.
  const openRe = new RegExp(`^[ \\t]*<(${tagAlt})(\\s[^>]*)?>`, "i");
  // Self-closing: <tag ... />  or <tag ... > on a single line with matching </tag>
  // We handle both by scanning line-by-line below.

  const lines = markdown.split("\n");
  const out: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i]!;
    const m = openRe.exec(line);
    if (m) {
      const tagName = m[1]!.toLowerCase();
      const closeTag = `</${tagName}>`;
      // Collect lines until we find the closing tag at the start of a line
      // (allowing leading whitespace). Support both same-line close and
      // multi-line blocks.
      const blockLines: string[] = [line];
      // Check if the opening line also contains the closing tag.
      if (line.toLowerCase().includes(closeTag)) {
        // Single-line block — done immediately.
        const html = blockLines.join("\n");
        const token = `${RAW_HTML_PLACEHOLDER_PREFIX}${counter++}`;
        rawBlocks.push({ token, html });
        out.push(token);
        i++;
        continue;
      }
      // Multi-line: gather until closing tag line.
      i++;
      let found = false;
      while (i < lines.length) {
        const l = lines[i]!;
        blockLines.push(l);
        if (l.trim().toLowerCase() === closeTag || l.trim().toLowerCase().startsWith(closeTag)) {
          found = true;
          i++;
          break;
        }
        i++;
      }
      const html = blockLines.join("\n");
      const token = `${RAW_HTML_PLACEHOLDER_PREFIX}${counter++}`;
      rawBlocks.push({ token, html });
      out.push(token);
    } else {
      out.push(line);
      i++;
    }
  }

  return { markdown: out.join("\n"), rawBlocks };
}

/**
 * After unified pipeline, restore raw HTML blocks from their LBRAW tokens.
 * The pipeline wraps each bare-text token in <p>TOKEN</p>; we replace the
 * entire <p> element.
 */
export function injectRawHtmlBlocks(html: string, rawBlocks: RawHtmlEntry[]): string {
  let result = html;
  for (const entry of rawBlocks) {
    const wrappedToken = `<p>${entry.token}</p>`;
    if (result.includes(wrappedToken)) {
      result = result.replace(wrappedToken, entry.html);
    } else {
      // Fallback: token may appear without <p> wrapper in some contexts.
      result = result.replace(entry.token, entry.html);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Copy-button wrapping (ADR-26)
// ---------------------------------------------------------------------------

/**
 * Wrap every <pre> element in a <div class="lb-pre-wrap"> and append a
 * sibling <button class="lb-copy"> for clipboard JS to wire up.
 *
 * Runs BEFORE injectMermaidSvgs so we don't wrap rendered SVG blocks.
 * Simple string-replace — mirrors the existing post-processing pattern.
 */
export function wrapPreElements(html: string): string {
  return html.replace(
    /(<pre(?:\s[^>]*)?>[\s\S]*?<\/pre>)/gi,
    '<div class="lb-pre-wrap">$1<button class="lb-copy" type="button" aria-label="Copy code">Copy</button></div>'
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Convert a Markdown string to an HTML body fragment.
 *
 * Used by both the HTML export pipeline (`html.ts`) and the generator
 * helpers (`sessions-doc.ts`) to render inline content.
 *
 * @param markdown       Source markdown string.
 * @param speakerBlocks  Optional speaker blocks extracted before this call.
 * @returns              HTML body fragment string.
 */
export async function markdownToHtml(
  markdown: string,
  speakerBlocks?: SpeakerBlock[],
): Promise<string> {
  // Phase 1: extract <details> blocks → tokens.
  const { markdown: withoutDetails, details } =
    preprocessDetailsPlaceholders(markdown);

  // Phase 1b: extract other raw HTML blocks → LBRAW tokens (CRITICAL-1 fix).
  // Runs AFTER details so nested <details> inside divs are already tokenized.
  const { markdown: withoutRawHtml, rawBlocks } =
    preprocessRawHtmlPlaceholders(withoutDetails);

  // Phase 2: extract mermaid fences → placeholders + SVG array.
  const { markdown: withPlaceholders, svgs } =
    await preprocessMermaidPlaceholders(withoutRawHtml);

  const processor = unified()
    .use(remarkParse)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeStringify);

  const file = await processor.process(withPlaceholders);
  let html = String(file);

  // Phase 3 (ADR-26): wrap <pre> elements before mermaid injection.
  html = wrapPreElements(html);

  // Phase 4: inject mermaid SVG divs in place of comment placeholders.
  html = injectMermaidSvgs(html, svgs);

  // Phase 5: restore <details> blocks.
  html = injectDetailsDivs(html, details);

  // Phase 5b: restore raw HTML blocks (CRITICAL-1 fix).
  html = injectRawHtmlBlocks(html, rawBlocks);

  // Phase 6 (speaker mode): inject speaker note divs.
  if (speakerBlocks && speakerBlocks.length > 0) {
    html = injectSpeakerDivs(html, speakerBlocks);
  }

  return html;
}
