/**
 * logbook summarize milestone [id|last] [--out <path>] [--json] [--no-stream]
 *
 * Summarizes a milestone's events using the LLM router.
 *
 * Mock mode (CI-safe):
 *   When LOGBOOK_LLM_MOCK=1 is set, injects a deterministic stub adapter
 *   that returns a templated summary without any real LLM calls.
 *   Same pattern as providers/test.ts (T7.D1 convention).
 *
 * Streaming mode (D2 policy):
 *   Tokens are streamed to stdout when ALL of:
 *     1. process.stdout.isTTY === true
 *     2. --no-stream flag was NOT provided
 *     3. --json flag was NOT provided (json mode never interleaves chunks)
 *     4. process.env.NODE_ENV !== "test" (belt-and-suspenders for test runners)
 *   Otherwise falls back to the silent generateText path.
 *
 * Exit codes:
 *   0 → ok:true
 *   1 → ok:false or any error (message written to stderr)
 *
 * Output:
 *   --json  → JSON { ok, summaryPath, bytes } or { ok, error }
 *   default → human-readable status line (streaming chunks precede final line when active)
 */

import { defineCommand } from "citty";
import { resolveProjectRoot, makePaths } from "../../../core/paths.js";
import { createRouter } from "../../../llm/provider-router.js";
import { summarizeMilestone } from "../../../llm/summarize.js";
import type { LlmAdapterCallInput } from "../../../types/llm.js";

/**
 * Deterministic mock adapter for LOGBOOK_LLM_MOCK=1 mode.
 * Returns a templated summary so integration tests never hit real LLM APIs.
 * When onChunk is provided, splits the canned text into chunks to exercise
 * the streaming wire end-to-end (D8 design decision).
 */
function mockSummaryAdapter(input: LlmAdapterCallInput): Promise<string> {
  const text =
    "## Mock Milestone Summary\n\nThis is a deterministic mock summary generated by LOGBOOK_LLM_MOCK=1.\n\n- Decisions: captured\n- Errors: resolved\n- Lessons: documented\n";

  if (input.onChunk) {
    const onChunk = input.onChunk;
    // Split into ~3 chunks at sentence boundaries for realistic streaming simulation.
    const parts = [
      "## Mock Milestone Summary\n\n",
      "This is a deterministic mock summary generated by LOGBOOK_LLM_MOCK=1.\n\n",
      "- Decisions: captured\n- Errors: resolved\n- Lessons: documented\n",
    ];
    return (async () => {
      for (const part of parts) {
        await Promise.resolve(); // micro-tick between chunks
        onChunk(part);
      }
      return text;
    })();
  }

  return Promise.resolve(text);
}

export default defineCommand({
  meta: {
    name: "milestone",
    description: "Summarize a milestone (id or 'last')",
  },
  args: {
    id: {
      type: "positional",
      required: false,
      default: "last",
      description: "Milestone id or 'last' (default: last)",
    },
    out: {
      type: "string",
      required: false,
      description: "Output path override (default: logbook/evidence/summaries/<id>.md)",
    },
    json: {
      type: "boolean",
      default: false,
      description: "Output as JSON",
    },
    stream: {
      type: "boolean",
      default: true,
      description: "Stream tokens to stdout (auto-disabled when not a TTY or with --no-stream)",
    },
  },
  async run({ args }) {
    let root: string;
    try {
      root = resolveProjectRoot();
    } catch (err) {
      process.stderr.write(
        `error: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      process.exit(1);
    }

    const paths = makePaths(root);
    const milestoneId = (args["id"] as string | undefined) ?? "last";
    const outPathArg = typeof args["out"] === "string" && args["out"]
      ? args["out"]
      : undefined;
    const isMock = process.env["LOGBOOK_LLM_MOCK"] === "1";
    const isJson = args["json"] === true;
    const streamFlag = args["stream"] !== false; // default true; --no-stream sets to false

    // D2 streaming activation policy: activate onChunk iff ALL conditions hold:
    //   1. TTY (not a pipe/redirect)
    //   2. --no-stream was NOT set
    //   3. --json was NOT set (json never interleaves chunks with the envelope)
    //   4. Not running inside vitest (belt-and-suspenders)
    const useStreaming =
      process.stdout.isTTY === true &&
      streamFlag &&
      !isJson &&
      process.env["NODE_ENV"] !== "test" &&
      process.env["VITEST"] === undefined;

    const onChunk = useStreaming
      ? (chunk: string) => { process.stdout.write(chunk); }
      : undefined;

    const router = createRouter({
      providersPath: paths.providersPath,
      ...(isMock && { mockAdapter: mockSummaryAdapter }),
      ...(isMock && { sleep: async () => {} }),
    });

    const result = await summarizeMilestone({
      router,
      paths,
      milestoneId,
      ...(outPathArg !== undefined && { outPath: outPathArg }),
      ...(onChunk !== undefined && { onChunk }),
    });

    // After streaming chunks, emit a newline before the status line so it
    // appears on its own line (only relevant in TTY streaming mode).
    if (useStreaming && result.ok) {
      process.stdout.write("\n");
    }

    if (args["json"]) {
      process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    } else {
      if (result.ok) {
        process.stdout.write(
          `ok: true\nsummaryPath: ${result.summaryPath ?? ""}\nbytes: ${result.bytes ?? 0}\n`,
        );
      } else {
        process.stderr.write(`error: ${result.error ?? "Unknown error"}\n`);
      }
    }

    process.exit(result.ok ? 0 : 1);
  },
});
