/**
 * logbook summarize project [--out <path>] [--json] [--no-stream]
 *
 * Summarizes the full project arc using the LLM router.
 *
 * Mock mode (CI-safe):
 *   When LOGBOOK_LLM_MOCK=1 is set, injects a deterministic stub adapter.
 *   Same pattern as providers/test.ts (T7.D1 convention).
 *
 * Streaming mode (D2 policy):
 *   Tokens are streamed to stdout when ALL of:
 *     1. process.stdout.isTTY === true
 *     2. --no-stream flag was NOT provided
 *     3. --json flag was NOT provided
 *     4. process.env.NODE_ENV !== "test"
 *
 * Exit codes:
 *   0 → ok:true
 *   1 → ok:false or any error (message written to stderr)
 *
 * Output:
 *   --json  → JSON { ok, summaryPath, bytes } or { ok, error }
 *   default → human-readable status line
 */

import { defineCommand } from "citty";
import { resolveProjectRoot, makePaths } from "../../../core/paths.js";
import { createRouter } from "../../../llm/provider-router.js";
import { summarizeProject } from "../../../llm/summarize.js";
import type { LlmAdapterCallInput } from "../../../types/llm.js";

/**
 * Deterministic mock adapter for LOGBOOK_LLM_MOCK=1 mode.
 * Returns a templated project summary without real LLM calls.
 * When onChunk is provided, splits the canned text into chunks (D8 design decision).
 */
function mockSummaryAdapter(input: LlmAdapterCallInput): Promise<string> {
  const text =
    "## Mock Project Summary\n\nThis is a deterministic mock project summary generated by LOGBOOK_LLM_MOCK=1.\n\n- Milestones: completed\n- Decisions: documented\n- Lessons: captured\n";

  if (input.onChunk) {
    const onChunk = input.onChunk;
    const parts = [
      "## Mock Project Summary\n\n",
      "This is a deterministic mock project summary generated by LOGBOOK_LLM_MOCK=1.\n\n",
      "- Milestones: completed\n- Decisions: documented\n- Lessons: captured\n",
    ];
    return (async () => {
      for (const part of parts) {
        await Promise.resolve();
        onChunk(part);
      }
      return text;
    })();
  }

  return Promise.resolve(text);
}

export default defineCommand({
  meta: {
    name: "project",
    description: "Summarize the full project arc",
  },
  args: {
    out: {
      type: "string",
      required: false,
      description: "Output path override (default: logbook/evidence/summaries/project.md)",
    },
    json: {
      type: "boolean",
      default: false,
      description: "Output as JSON",
    },
    stream: {
      type: "boolean",
      default: true,
      description: "Stream tokens to stdout (auto-disabled when not a TTY or with --no-stream)",
    },
  },
  async run({ args }) {
    let root: string;
    try {
      root = resolveProjectRoot();
    } catch (err) {
      process.stderr.write(
        `error: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      process.exit(1);
    }

    const paths = makePaths(root);
    const outPathArg = typeof args["out"] === "string" && args["out"]
      ? args["out"]
      : undefined;
    const isMock = process.env["LOGBOOK_LLM_MOCK"] === "1";
    const isJson = args["json"] === true;
    const streamFlag = args["stream"] !== false;

    // D2 streaming activation policy: same as summarize/milestone.ts.
    const useStreaming =
      process.stdout.isTTY === true &&
      streamFlag &&
      !isJson &&
      process.env["NODE_ENV"] !== "test" &&
      process.env["VITEST"] === undefined;

    const onChunk = useStreaming
      ? (chunk: string) => { process.stdout.write(chunk); }
      : undefined;

    const router = createRouter({
      providersPath: paths.providersPath,
      ...(isMock && { mockAdapter: mockSummaryAdapter }),
      ...(isMock && { sleep: async () => {} }),
    });

    const result = await summarizeProject({
      router,
      paths,
      ...(outPathArg !== undefined && { outPath: outPathArg }),
      ...(onChunk !== undefined && { onChunk }),
    });

    if (useStreaming && result.ok) {
      process.stdout.write("\n");
    }

    if (args["json"]) {
      process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    } else {
      if (result.ok) {
        process.stdout.write(
          `ok: true\nsummaryPath: ${result.summaryPath ?? ""}\nbytes: ${result.bytes ?? 0}\n`,
        );
      } else {
        process.stderr.write(`error: ${result.error ?? "Unknown error"}\n`);
      }
    }

    process.exit(result.ok ? 0 : 1);
  },
});
