/**
 * logbook summarize project [--out <path>] [--json]
 *
 * Summarizes the full project arc using the LLM router.
 *
 * Mock mode (CI-safe):
 *   When LOGBOOK_LLM_MOCK=1 is set, injects a deterministic stub adapter.
 *   Same pattern as providers/test.ts (T7.D1 convention).
 *
 * Exit codes:
 *   0 → ok:true
 *   1 → ok:false or any error (message written to stderr)
 *
 * Output:
 *   --json  → JSON { ok, summaryPath, bytes } or { ok, error }
 *   default → human-readable status line
 */

import { defineCommand } from "citty";
import { resolveProjectRoot, makePaths } from "../../../core/paths.js";
import { createRouter } from "../../../llm/provider-router.js";
import { summarizeProject } from "../../../llm/summarize.js";
import type { LlmAdapterCallInput } from "../../../types/llm.js";

/**
 * Deterministic mock adapter for LOGBOOK_LLM_MOCK=1 mode.
 * Returns a templated project summary without real LLM calls.
 */
function mockSummaryAdapter(_input: LlmAdapterCallInput): Promise<string> {
  return Promise.resolve(
    "## Mock Project Summary\n\nThis is a deterministic mock project summary generated by LOGBOOK_LLM_MOCK=1.\n\n- Milestones: completed\n- Decisions: documented\n- Lessons: captured\n",
  );
}

export default defineCommand({
  meta: {
    name: "project",
    description: "Summarize the full project arc",
  },
  args: {
    out: {
      type: "string",
      required: false,
      description: "Output path override (default: logbook/evidence/summaries/project.md)",
    },
    json: {
      type: "boolean",
      default: false,
      description: "Output as JSON",
    },
  },
  async run({ args }) {
    let root: string;
    try {
      root = resolveProjectRoot();
    } catch (err) {
      process.stderr.write(
        `error: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      process.exit(1);
    }

    const paths = makePaths(root);
    const outPathArg = typeof args["out"] === "string" && args["out"]
      ? args["out"]
      : undefined;
    const isMock = process.env["LOGBOOK_LLM_MOCK"] === "1";

    const router = createRouter({
      providersPath: paths.providersPath,
      ...(isMock && { mockAdapter: mockSummaryAdapter }),
      ...(isMock && { sleep: async () => {} }),
    });

    const result = await summarizeProject({
      router,
      paths,
      ...(outPathArg !== undefined && { outPath: outPathArg }),
    });

    if (args["json"]) {
      process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    } else {
      if (result.ok) {
        process.stdout.write(
          `ok: true\nsummaryPath: ${result.summaryPath ?? ""}\nbytes: ${result.bytes ?? 0}\n`,
        );
      } else {
        process.stderr.write(`error: ${result.error ?? "Unknown error"}\n`);
      }
    }

    process.exit(result.ok ? 0 : 1);
  },
});
