/**
 * logbook teaching-script [id|last] [--out <dir>] [--json]
 *
 * Generates an instructor-facing teaching script for a milestone (LLM-backed).
 *
 * Decision T12.D1: standalone command — cleaner separation from `logbook build`
 * (build stays deterministic-only; teaching-script is LLM-backed).
 *
 * Mock mode (CI-safe):
 *   When LOGBOOK_LLM_MOCK=1 is set, injects a deterministic stub adapter that
 *   returns a templated teaching script without any real LLM calls.
 *   Same pattern as summarize/milestone.ts (T8 convention).
 *
 * Exit codes:
 *   0 → ok:true
 *   1 → ok:false or any error (message written to stderr)
 *
 * Output:
 *   --json  → JSON { ok, filePath, bytes } or { ok, error }
 *   default → human-readable status line
 */

import { defineCommand } from "citty";
import { resolveProjectRoot, makePaths } from "../../core/paths.js";
import { createRouter } from "../../llm/provider-router.js";
import { generateTeachingScript } from "../../generate/teaching-script-doc.js";
import type { LlmAdapterCallInput } from "../../types/llm.js";

/**
 * Deterministic mock adapter for LOGBOOK_LLM_MOCK=1 mode.
 * Returns a structured teaching-script template so integration tests
 * never hit real LLM APIs.
 */
function mockTeachingScriptAdapter(_input: LlmAdapterCallInput): Promise<string> {
  return Promise.resolve(
    [
      "## Overview",
      "",
      "This is a deterministic mock teaching script generated by LOGBOOK_LLM_MOCK=1.",
      "",
      "## Key Decisions",
      "",
      "- All decisions have been captured and documented.",
      "",
      "## Common Pitfalls",
      "",
      "- Errors were encountered and resolved during this milestone.",
      "",
      "## Lessons to Emphasize",
      "",
      "- Lessons have been extracted from the milestone events.",
      "",
      "## Discussion Prompts",
      "",
      "- What would you do differently?",
      "- How do these decisions affect the architecture?",
    ].join("\n"),
  );
}

export default defineCommand({
  meta: {
    name: "teaching-script",
    description: "Generate an instructor-facing teaching script (LLM-backed)",
  },
  args: {
    id: {
      type: "positional",
      required: false,
      default: "last",
      description: "Milestone id or 'last' (default: last)",
    },
    out: {
      type: "string",
      required: false,
      description: "Output directory override (default: logbook/teaching-scripts/)",
    },
    json: {
      type: "boolean",
      default: false,
      description: "Output as JSON",
    },
  },
  async run({ args }) {
    let root: string;
    try {
      root = resolveProjectRoot();
    } catch (err) {
      process.stderr.write(
        `error: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      process.exit(1);
    }

    const paths = makePaths(root);
    const milestoneId = (args["id"] as string | undefined) ?? "last";
    const outDir = args["out"] as string | undefined;
    const isMock = process.env["LOGBOOK_LLM_MOCK"] === "1";

    const router = createRouter({
      providersPath: paths.providersPath,
      ...(isMock && { mockAdapter: mockTeachingScriptAdapter }),
      ...(isMock && { sleep: async () => {} }),
    });

    const result = await generateTeachingScript({
      router,
      paths,
      milestoneId,
      ...(outDir !== undefined && { outDir }),
    });

    if (args["json"]) {
      process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    } else {
      if (result.ok) {
        process.stdout.write(
          `ok: true\nfilePath: ${result.filePath ?? ""}\nbytes: ${result.bytes ?? 0}\n`,
        );
      } else {
        process.stderr.write(`error: ${result.error ?? "Unknown error"}\n`);
      }
    }

    process.exit(result.ok ? 0 : 1);
  },
});
