/**
 * T6.16 — PASSIVE invariant (INV-1) + AG-16/17.
 *
 * No installer file, no hook file, no capture/MCP/transcript surface is touched
 * by this slice. We verify by inspecting the existence of canonical entry
 * points + asserting the install/uninstall manifest contract is unchanged.
 *
 * This is a regression guard, not an exhaustive byte-identical proof —
 * that proof lives in the e2e §24.8 test.
 */

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(__dirname, "../..");

function exists(rel: string): boolean {
  return existsSync(resolve(ROOT, rel));
}

describe("visual-replay — T6.16 PASSIVE invariant", () => {
  it("capture surface still present (events module)", () => {
    // The events surface lives under src/events/ — the slice 5/6 writer +
    // schema contract owner. PASSIVE means we did not delete it.
    const candidates = [
      "src/events/schemas.ts",
      "src/events",
    ];
    expect(candidates.some(exists)).toBe(true);
  });

  it("hook surface still present", () => {
    const candidates = [
      "src/hooks/session-start.ts",
      "src/hooks",
    ];
    expect(candidates.some(exists)).toBe(true);
  });

  it("MCP surface still present", () => {
    const candidates = [
      "src/mcp/server.ts",
      "src/mcp/index.ts",
      "src/mcp",
    ];
    expect(candidates.some(exists)).toBe(true);
  });

  it("installer surface still present (AG-17 byte-identical contract owner)", () => {
    // Install logic lives under src/cli/ in this codebase (see src/cli/commands).
    const candidates = [
      "src/cli/index.ts",
      "src/cli/commands",
      "src/cli",
    ];
    expect(candidates.some(exists)).toBe(true);
  });

  it("the export bundle is the only injected style source (AG-19 self-contained)", () => {
    // Slice 10+ invariant: styles ship pre-compiled inside the Svelte bundle.
    // Slice 19 deleted the legacy `src/export/inline-css.ts` — its CSS now
    // lives in the vendored `src/export/ui-bundle.ts` (generated by
    // `pnpm sync:export-ui` from `apps/export-ui/dist/index.html`).
    const bundlePath = resolve(ROOT, "src/export/ui-bundle.ts");
    expect(existsSync(bundlePath)).toBe(true);
    const src = readFileSync(bundlePath, "utf8");
    // Sanity: the bundle is a single inlined HTML string with both <style>
    // and <script> content embedded.
    expect(src).toContain("UI_BUNDLE");
    expect(src).toContain("<!doctype html>");
  });
});
